### ISSUE TITLE
I get lots of errors when I run with -d

### ISSUE THREAD

**Issue by munntjlx** [TURROKS/CVE_Prioritizer#3]
Great app, but I was trying to run using the -d flag and I get TONS of errors:

```sh
cvepri -d

#    ______   ______
#   / ___/ | / / __/
#  / /__ | |/ / _/
#  \___/_|___/___/        _ __  _
#    / _ \____(_)__  ____(_) /_(_)__ ___ ____
#   / ___/ __/ / _ \/ __/ / __/ /_ // -_) __/
#  /_/  /_/ /_/\___/_/ /_/\__/_//__/\__/_/
#                                  BY TURROKS

CVE-ID            Priority
------------------------------
CVE-2023-1389     Error
CVE-2023-20869    Error
CVE-2023-29489    Error
CVE-2023-28771    Error
CVE-2023-27524    Error
CVE-2023-27350    Error
CVE-2023-21839    Error
CVE-2021-45046    Error
CVE-2023-27532    Error
CVE-2023-21932    Error
```
I am using python 3.9.7 and Darwin LNGRDUM-C02Z705DLVDQ 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64 

Mac Monterey 12.6.5 INTEL

Thomas

**Comment by TURROKS** [comment]
Hi Thomas, thanks for your kind words and for creating an issue. I will try to recreate the problem and get back to you soon. 

Does it only happen with the -d flag? Does it work properly if you try to get the info for one of those CVEs using the normal -c function?

**Comment by munntjlx** [comment]
It seems to work fine on specific CVE's, just the -d

________________________________________

**Comment by TURROKS** [comment]
Hi Thomas, thanks for getting back to me, Im able to replicate now, it looks like it's an issue from NIST's API, I'll work on a solution for this issue and also add more detailed error messages.

Best,
Mario

**Comment by TURROKS** [comment]
Hi Thomas, 

The errors are associated with NIST rate-limiting requests that don't provide an API key.

I have added support for doing so; after testing the tool with and without the Key, it looks like the issue is resolved.

You can request a key here https://nvd.nist.gov/developers/request-an-api-key

Once you get the Key, you can add it to the new .env file included in the project like so NIST_API=your-key-goes-here

Please make sure to install the new required libraries as well.

Best,
Mario

**Comment by TURROKS** [comment]
Hey Thomas, 

Im closing this issue for now, please feel free to re-open it if the issue persists after using the API

**Comment by munntjlx** [comment]
I just ran it with a key. works fine now. Thanks for the update!
